DROP TABLE IF EXISTS Keys;
CREATE TABLE IF NOT EXISTS Keys (id INTEGER PRIMARY KEY AUTOINCREMENT, ActivationKey TEXT UNIQUE NOT NULL, UserEmail TEXT NOT NULL, MachineID TEXT, DateCreated TEXT NOT NULL);

